# Generated by Django 4.0.4 on 2022-06-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickerdetails',
            name='ticker_end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tickerdetails',
            name='ticker_start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tickerhistory',
            name='ticker_end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tickerhistory',
            name='ticker_start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
